name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          cache: npm
      - name: Bump version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          npm version ${{ inputs.bump-type }}
          git push --follow-tags
